version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: shiftme-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: server_container
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

volumes:
  pgdata:

    
